### ISSUE TITLE
MacOS arm64 1.0.0 beta 5 is corrupt and can't be opened

### ISSUE THREAD

**Issue by steliosaa** [njzydark/PS4RPS#1]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/26743665/154238063-4d8efd30-e4b4-48b4-848c-055ab002ef54.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/26743665/154238248-493fa14f-3635-4d1e-bd76-c5304d9fe127.png">

**Comment by njzydark** [comment]
See faq https://github.com/njzydark/PS4RPS#faq

<img width="950" alt="image" src="https://user-images.githubusercontent.com/19601720/154246013-94f2a651-a013-4e57-9cff-f3c2e96dae45.png">
