### ISSUE TITLE
Can't scan files from server

### ISSUE THREAD

**Issue by Lvieira21** [njzydark/PS4RPS#3]
I'm currently struggling to scan files to send to ps4. I keep getting this error: 
"Get file server files error
Request failed with status code 500"

I'm trying to configure a static server. I'm using 1.0.0-beta.5. 
The message where it says my local server is configured shows up, but I keep receiving this error

**Comment by njzydark** [comment]
Please try beta.6 https://github.com/njzydark/PS4RPS/releases/tag/v1.0.0-beta.6
