### ISSUE TITLE
文件名和路径中不能含有空格

### ISSUE THREAD

**Issue by Saopanda** [njzydark/PS4RPS#5]
会报500错，但是看不到具体什么错误，只能猜测。nas等排除一轮，发现是文件名中空格导致，去掉即可。
遗憾的是我下载的绝大部分游戏名及路径中都包含了空格

**Comment by Saopanda** [comment]
猜测将文件提供端的地址链接 urlencode 就行

**Comment by njzydark** [comment]
能发下network面板里的请求信息吗

**Comment by Saopanda** [comment]
在用win客户端，没有找到控制台。网页版的运行在https上，我本地的服务都是http的，连接被浏览器拒绝，折腾无果放弃了

**Comment by njzydark** [comment]
> 在用win客户端，没有找到控制台。网页版的运行在https上，我本地的服务都是http的，连接被浏览器拒绝，折腾无果放弃了

用webdav发送文件时链接是转了的 https://xxx.com/PS4/homebrew/hello_world%20%E4%B8%AD%E6%96%87%20%E6%B5%8B%E8%AF%95.pkg 如果不行那应该是ps4上那个RPI的问题了

**Comment by njzydark** [comment]
> 在用win客户端，没有找到控制台。网页版的运行在https上，我本地的服务都是http的，连接被浏览器拒绝，折腾无果放弃了

试下这个 http的 http://ps4rps.njzydark.com/

**Comment by Saopanda** [comment]
Access to XMLHttpRequest at 'http://192.168.1.201:5005/' from origin 'http://ps4rps.njzydark.com' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

**Comment by njzydark** [comment]
> Access to XMLHttpRequest at 'http://192.168.1.201:5005/' from origin 'http://ps4rps.njzydark.com' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

这个5005是群晖的webdav端口吧 群晖这个webdav没开跨域 win客户端按键盘ctr+shift+i试下 应该是可以唤出开发者面板的

**Comment by Saopanda** [comment]
win客户端成功打开控制台面板
{
    "status": "fail",
    "error": "Unable to set up prerequisites for package 'http://xxx@192.168.1.201:5005/3TLSAFE/Moving Out/Moving Out-GAMEKEGS/Moving Out.v1.01.CUSA17675-GAMEKEGS.pkg': Unable to download package header for 'http://xxxx@192.168.1.201:"
}

>

**Comment by njzydark** [comment]
> win客户端成功打开控制台面板 { "status": "fail", "error": "Unable to set up prerequisites for package 'http://xxx@192.168.1.201:5005/3TLSAFE/Moving Out/Moving Out-GAMEKEGS/Moving Out.v1.01.CUSA17675-GAMEKEGS.pkg': Unable to download package header for 'http://xxxx@192.168.1.201:" }
> 
> >

那就是rpi那边的问题了，跟sender无关了。rpi那边的问题我这里也不太好解决，目前如果想无线安装只能改目录格式了

**Comment by njzydark** [comment]
try this on your ps4 https://github.com/njzydark/ps4_remote_pkg_installer-OOSDK/releases/tag/1.02
