### ISSUE TITLE
make the web version to http

### ISSUE THREAD

**Issue by remlei** [njzydark/PS4RPS#6]
`(Mixed Content: The page at 'https://ps4rps.vercel.app/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.254.2:90/ps4/'. This request has been blocked; the content must be served over HTTPS.)`

The error it display is "Get file server files error Network Error", making your own self signed certificates is kinda pain in the ass since the browser is rejecting, I can probably force it but meh, just make the web version with http and probably that should fix the issue.

Browser used: Edge, Chrome and Firefox

**Comment by njzydark** [comment]
Try this http://ps4rps.njzydark.com

**Comment by remlei** [comment]
unfortunately it still have issue regarding CORS

`Access to XMLHttpRequest at 'http://192.168.254.2:90/ps4/' from origin 'http://ps4rps.njzydark.com' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space "private".`

I guess well be having issues with this if the website is hosted over the internet where the webdav hosted on the NAS is under local IP address.

I did work around on it though but this involves basically fetch the website data of that site and host it locally on my NAS and now it works.

![rpi](https://user-images.githubusercontent.com/9265995/156950090-e8184b43-c78d-4877-9f98-5043f436bf6c.png)

**Comment by njzydark** [comment]
> unfortunately it still have issue regarding CORS
> 
> `Access to XMLHttpRequest at 'http://192.168.254.2:90/ps4/' from origin 'http://ps4rps.njzydark.com' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space "private".`
> 

This is because the server(192.168.254.2:90) not enable cors.  On my NAS, I use this docker image to create webdav server: https://github.com/hacdias/webdav#cors

**Comment by njzydark** [comment]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/19601720/157037083-d8355fc8-8a7d-49ce-b822-b7ed637c6c93.png">

**Comment by remlei** [comment]
ill probably just close this issue since this is no longer a related, unfortunately this may be a issue on some NASes, I have already tested this on several instances of docker containers with CORS definitely enabled on the webserver and/or different NAS with their own webserver apps but they all have the same issue, not unless I disabled the CORS on my browser which is a very bad idea or use the public sided IP address which im not doing and pointless.

this may actually end up like a "it works for me" kind of situation.

**Comment by njzydark** [comment]
> it seems to work only on firefox, already tried several browser like Chrome, Brave, Edge, Chromium, all have the same CORS error.

On the issue of CORS, the easiest way is to open the developer tools and check whether the response header has a cors response header, the correct cors setting should be like this

<img width="627" alt="image" src="https://user-images.githubusercontent.com/19601720/157152936-620a1fb1-416c-4cd3-a025-de83dd3d0ba3.png">
