### ISSUE TITLE
PS4RPS报错

### ISSUE THREAD

**Issue by qin9125** [njzydark/PS4RPS#9]
首先感谢楼主的辛苦码代码，你改进的RPI 真的好用，其他版本的对于 9.0 系统失效的用不了，我用了你开发的电脑端 PS4RPS 和其他开发者的PS4 Remote PKG Sender V2 我觉都挺好的，你这个 app 能增加个测试 ps4 连通性按钮吗？还有就是我不知道为啥我不能安装报错？谢谢
<img width="986" alt="iShot2022-04-06 11 42 32" src="https://user-images.githubusercontent.com/32502941/161891837-9561bb82-ee3a-48fa-b0a6-11e7fc8d29bd.png">

**Comment by njzydark** [comment]
验证连通性这个争取下个版本加上，目前在开发新UI，至于你现在这个安装失败可以看下是不是你ps4 host的地址没有加http:// , 目前这个地方是需要加上完整的http地址的

**Comment by njzydark** [comment]
issue置顶了交流群链接，可以进群沟通 https://github.com/njzydark/PS4RPS/issues/10

**Comment by qin9125** [comment]
> issue置顶了交流群链接，可以进群沟通 #10

谢谢，完整的地址是指什么？

**Comment by njzydark** [comment]
可以试一下新版本 https://github.com/njzydark/PS4RPS/releases/tag/v1.0.0-beta.7
